version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  groups:
    artifact-actions:
      patterns:
        - "actions/upload-artifact"
        - "actions/download-artifact"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "zod"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@types/node"
      update-types: ["version-update:semver-major"]
